# Generated by Django 4.2.5 on 2023-10-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weather", options={"ordering": ["-retrieved_on"]},
        ),
        migrations.RenameField(
            model_name="weather", old_name="created_on", new_name="retrieved_on",
        ),
    ]
