# Generated by Django 4.2.5 on 2023-10-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=5)),
                ("street", models.CharField(max_length=50)),
            ],
            options={"db_table": "tbl_customer",},
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=5)),
                ("street", models.CharField(max_length=50)),
            ],
            options={"db_table": "tbl_shop",},
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=10, unique=True)),
                ("carrier", models.CharField(max_length=10)),
                ("article_name", models.CharField(max_length=50)),
                ("article_quantity", models.PositiveSmallIntegerField()),
                ("article_price", models.PositiveIntegerField()),
                ("sku", models.CharField(max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in-transit", "In Transit"),
                            ("inbound-scan", "Inbound Scan"),
                            ("delivery", "Delivery"),
                            ("transit", "Transit"),
                            ("scanned", "Scanned"),
                        ],
                        default="in-transit",
                        max_length=12,
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="shipment.customer",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="shipment.shop",
                    ),
                ),
            ],
            options={"db_table": "tbl_shipment",},
        ),
        migrations.AddField(
            model_name="customer",
            name="shops",
            field=models.ManyToManyField(
                related_name="customers",
                through="shipment.Shipment",
                to="shipment.shop",
            ),
        ),
    ]
