# Generated by Django 4.2.5 on 2023-10-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="name", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="article",
            name="sku",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
