# Generated by Django 4.2.5 on 2023-10-15 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0002_alter_article_name_alter_article_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleshipment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_shipments",
                to="shipment.article",
            ),
        ),
        migrations.AlterField(
            model_name="articleshipment",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipment_articles",
                to="shipment.shipment",
            ),
        ),
    ]
