# Generated by Django 4.2.5 on 2023-10-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0003_alter_articleshipment_article_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="shipments",),
        migrations.AddField(
            model_name="shipment",
            name="article",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="shipment.article",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="article_quantity",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="carrier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="shipment.carrier",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="ArticleShipment",),
    ]
